export const DOODLES = [
  {
    id: "star",
    src: "/images/Hero/star.png",
    alt: "Star Doodle",
    className: "animate-pulse",
    top: 76.01,
    left: 48.65,
    width: 4,
    scale: 1.4,
    rotation: -11,
  },
  {
    id: "circle",
    src: "/images/Hero/AroundCircle.png",
    alt: "Circle Doodle",
    className: "opacity-80",
    top: 66.3,
    left: 25.52,
    width: 50,
    scale: 0.45,
    rotation: 0,
    isCentered: false,
  },
  {
    id: "heart",
    src: "/images/Hero/love.png",
    alt: "Heart Doodle",
    className: "opacity-90",
    top: 73.15,
    left: 57.92,
    width: 3,
    scale: 1,
    rotation: 0,
  },
  {
    id: "heart-2",
    src: "/images/Hero/love.png",
    alt: "Heart Doodle",
    className: "opacity-90",
    top: 69.66,
    left: 39.87,
    width: 3,
    scale: 1,
    rotation: -44,
  },
  {
    id: "white-circle",
    src: "/images/Hero/white cricel.png",
    alt: "White Circle Doodle",
    className: "opacity-60",
    top: 79.21,
    left: 51.9,
    width: 8,
    scale: 0.8,
    rotation: 0,
  },
  {
    id: "boy-head",
    src: "/images/Hero/Boy_Head.png",
    alt: "Boy Head Doodle",
    className: "",
    top: 61.94,
    left: 43.49,
    width: 6,
    scale: 1.25,
    rotation: 0,
  },
  {
    id: "girl-head",
    src: "/images/Hero/Girl_Head.png",
    alt: "Girl Head Doodle",
    className: "",
    top: 67.36,
    left: 52.04,
    width: 6,
    scale: 1,
    rotation: 0,
  },
];

export const SOCIAL_LINKS = [
  { id: "Linkedin", url: "https://www.linkedin.com/company/resonance-rehab/" },
  { id: "Insta", url: "https://www.instagram.com/resonancerehab?igsh=NG5oaTByZjAwa3My" },
  { id: "fb", url: "https://www.facebook.com/profile.php?id=61587608773411" }, 
  { id: "Whatsapp", url: "https://wa.me/918921065634" },
  { id: "Mail", url: "https://mail.google.com/mail/?view=cm&fs=1&to=info@resonancerehab.com" },
];
